name: global_configs
description: A flutter package to manage application configurations via singleton pattern.
version: 1.0.0+2
author: Mehdi Zarepour
homepage: https://github.com/mehdizarepour/flutter-global-configs
repository: https://github.com/mehdizarepour/flutter-global-configs

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
 